version: "3.9"
services:
  api:
    build: .
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000
    ports:
      - 5000:5000
      - 5001:5001
    expose:
      - 5000:80
    volumes:
      - ~/.aspnet/https:/https:ro
    depends_on:
      - db
  db:
    volumes:
      - db_data:/var/opt/mssql/data
    image: mcr.microsoft.com/mssql/server:2017-latest
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Password123"
      ACCEPT_EULA: "Y"
  client:
    build: ./MVCApi.Client
    ports:
      - 3000:3000
      - 9229:9229
    depends_on:
      - api
    volumes:
      - type: bind
        source: ./MVCApi.Client
        target: /app
      - /app/node_modules/
  angular_client:
    build: ./MVCApi.AngularClient
    ports:
      - 4200:4200
    depends_on:
      - api
    volumes:
    - type: bind
      source: ./MVCApi.AngularClient
      target: /app
    - /app/node_modules/
volumes:
  db_data: null
