version: "3.9"
services:
  api:
    build: .
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:5001;http://+:5000
      - ASPNETCORE_Kestrel__Certificates__Default__Password=crypticpassword
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    ports:
      - 5000:5000
      - 5001:5001
    volumes:
      - ~/.aspnet/https:/https:ro
    depends_on:
      - db
  db:
    volumes:
      - db_data:/var/opt/mssql/data
    image: mcr.microsoft.com/mssql/server:2017-latest
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Password123"
      ACCEPT_EULA: "Y"
  client:
    build: ./MVCApi.Client
    ports:
      - 3000:3000
    depends_on:
      - api
    volumes:
      - /app/node_modules/
      - type: bind
        source: ./MVCApi.Client
        target: /app

volumes:
  db_data:
