/**
 * MVCApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type OrderState = 0 | 1 | 2;

export const OrderState = {
    NUMBER_0: 0 as OrderState,
    NUMBER_1: 1 as OrderState,
    NUMBER_2: 2 as OrderState
};

