export * from './address.service';
import { AddressService } from './address.service';
export * from './cart.service';
import { CartService } from './cart.service';
export * from './category.service';
import { CategoryService } from './category.service';
export * from './contactInfo.service';
import { ContactInfoService } from './contactInfo.service';
export * from './currency.service';
import { CurrencyService } from './currency.service';
export * from './customer.service';
import { CustomerService } from './customer.service';
export * from './order.service';
import { OrderService } from './order.service';
export * from './product.service';
import { ProductService } from './product.service';
export * from './user.service';
import { UserService } from './user.service';
export const APIS = [AddressService, CartService, CategoryService, ContactInfoService, CurrencyService, CustomerService, OrderService, ProductService, UserService];
