/* tslint:disable */
/* eslint-disable */
/**
 * MVCApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    ContactInfoDto,
    ContactInfoDtoFromJSON,
    ContactInfoDtoToJSON,
    EditContactInfo,
    EditContactInfoFromJSON,
    EditContactInfoToJSON,
} from '../models';

export interface ApiContactInfoEditContactInfoIdPutRequest {
    id: string;
    editContactInfo?: EditContactInfo;
}

export interface ApiContactInfoGetContactInfoByIdIdGetRequest {
    id: string;
}

/**
 * 
 */
export class ContactInfoApi extends runtime.BaseAPI {

    /**
     */
    async apiContactInfoEditContactInfoIdPutRaw(requestParameters: ApiContactInfoEditContactInfoIdPutRequest): Promise<runtime.ApiResponse<string>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling apiContactInfoEditContactInfoIdPut.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/ContactInfo/EditContactInfo/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: EditContactInfoToJSON(requestParameters.editContactInfo),
        });

        return new runtime.TextApiResponse(response) as any;
    }

    /**
     */
    async apiContactInfoEditContactInfoIdPut(requestParameters: ApiContactInfoEditContactInfoIdPutRequest): Promise<string> {
        const response = await this.apiContactInfoEditContactInfoIdPutRaw(requestParameters);
        return await response.value();
    }

    /**
     */
    async apiContactInfoGetContactInfoByIdIdGetRaw(requestParameters: ApiContactInfoGetContactInfoByIdIdGetRequest): Promise<runtime.ApiResponse<ContactInfoDto>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling apiContactInfoGetContactInfoByIdIdGet.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/ContactInfo/GetContactInfoById/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => ContactInfoDtoFromJSON(jsonValue));
    }

    /**
     */
    async apiContactInfoGetContactInfoByIdIdGet(requestParameters: ApiContactInfoGetContactInfoByIdIdGetRequest): Promise<ContactInfoDto> {
        const response = await this.apiContactInfoGetContactInfoByIdIdGetRaw(requestParameters);
        return await response.value();
    }

}
