/* tslint:disable */
/* eslint-disable */
/**
 * MVCApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    ImportCurrencies,
    ImportCurrenciesFromJSON,
    ImportCurrenciesToJSON,
} from '../models';

export interface ApiCurrencyImportCurrenciesPostRequest {
    importCurrencies?: ImportCurrencies;
}

/**
 * 
 */
export class CurrencyApi extends runtime.BaseAPI {

    /**
     */
    async apiCurrencyImportCurrenciesPostRaw(requestParameters: ApiCurrencyImportCurrenciesPostRequest): Promise<runtime.ApiResponse<Array<string>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/Currency/ImportCurrencies`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ImportCurrenciesToJSON(requestParameters.importCurrencies),
        });

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     */
    async apiCurrencyImportCurrenciesPost(requestParameters: ApiCurrencyImportCurrenciesPostRequest): Promise<Array<string>> {
        const response = await this.apiCurrencyImportCurrenciesPostRaw(requestParameters);
        return await response.value();
    }

}
