/* tslint:disable */
/* eslint-disable */
/**
 * MVCApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    CreateProduct,
    CreateProductFromJSON,
    CreateProductToJSON,
    ProductDto,
    ProductDtoFromJSON,
    ProductDtoToJSON,
    ProductDtoIPaginatedList,
    ProductDtoIPaginatedListFromJSON,
    ProductDtoIPaginatedListToJSON,
} from '../models';

export interface ApiProductCreateProductPostRequest {
    createProduct?: CreateProduct;
}

export interface ApiProductGetAllProductsGetRequest {
    currencyCode?: string | null;
}

export interface ApiProductGetPaginatedProductsByCategoryGetRequest {
    pageNumber?: number;
    pageSize?: number;
    currencyCode?: string | null;
    categoryId?: string;
}

export interface ApiProductGetPaginatedProductsGetRequest {
    pageNumber?: number;
    pageSize?: number;
    currencyCode?: string | null;
}

export interface ApiProductGetProductByIdIdGetRequest {
    id: string;
    currencyCode?: string | null;
}

/**
 * 
 */
export class ProductApi extends runtime.BaseAPI {

    /**
     */
    async apiProductCreateProductPostRaw(requestParameters: ApiProductCreateProductPostRequest): Promise<runtime.ApiResponse<string>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/Product/CreateProduct`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateProductToJSON(requestParameters.createProduct),
        });

        return new runtime.TextApiResponse(response) as any;
    }

    /**
     */
    async apiProductCreateProductPost(requestParameters: ApiProductCreateProductPostRequest): Promise<string> {
        const response = await this.apiProductCreateProductPostRaw(requestParameters);
        return await response.value();
    }

    /**
     */
    async apiProductGetAllProductsGetRaw(requestParameters: ApiProductGetAllProductsGetRequest): Promise<runtime.ApiResponse<Array<ProductDto>>> {
        const queryParameters: any = {};

        if (requestParameters.currencyCode !== undefined) {
            queryParameters['currencyCode'] = requestParameters.currencyCode;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/Product/GetAllProducts`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ProductDtoFromJSON));
    }

    /**
     */
    async apiProductGetAllProductsGet(requestParameters: ApiProductGetAllProductsGetRequest): Promise<Array<ProductDto>> {
        const response = await this.apiProductGetAllProductsGetRaw(requestParameters);
        return await response.value();
    }

    /**
     */
    async apiProductGetPaginatedProductsByCategoryGetRaw(requestParameters: ApiProductGetPaginatedProductsByCategoryGetRequest): Promise<runtime.ApiResponse<ProductDtoIPaginatedList>> {
        const queryParameters: any = {};

        if (requestParameters.pageNumber !== undefined) {
            queryParameters['pageNumber'] = requestParameters.pageNumber;
        }

        if (requestParameters.pageSize !== undefined) {
            queryParameters['pageSize'] = requestParameters.pageSize;
        }

        if (requestParameters.currencyCode !== undefined) {
            queryParameters['currencyCode'] = requestParameters.currencyCode;
        }

        if (requestParameters.categoryId !== undefined) {
            queryParameters['categoryId'] = requestParameters.categoryId;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/Product/GetPaginatedProductsByCategory`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => ProductDtoIPaginatedListFromJSON(jsonValue));
    }

    /**
     */
    async apiProductGetPaginatedProductsByCategoryGet(requestParameters: ApiProductGetPaginatedProductsByCategoryGetRequest): Promise<ProductDtoIPaginatedList> {
        const response = await this.apiProductGetPaginatedProductsByCategoryGetRaw(requestParameters);
        return await response.value();
    }

    /**
     */
    async apiProductGetPaginatedProductsGetRaw(requestParameters: ApiProductGetPaginatedProductsGetRequest): Promise<runtime.ApiResponse<ProductDtoIPaginatedList>> {
        const queryParameters: any = {};

        if (requestParameters.pageNumber !== undefined) {
            queryParameters['pageNumber'] = requestParameters.pageNumber;
        }

        if (requestParameters.pageSize !== undefined) {
            queryParameters['pageSize'] = requestParameters.pageSize;
        }

        if (requestParameters.currencyCode !== undefined) {
            queryParameters['currencyCode'] = requestParameters.currencyCode;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/Product/GetPaginatedProducts`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => ProductDtoIPaginatedListFromJSON(jsonValue));
    }

    /**
     */
    async apiProductGetPaginatedProductsGet(requestParameters: ApiProductGetPaginatedProductsGetRequest): Promise<ProductDtoIPaginatedList> {
        const response = await this.apiProductGetPaginatedProductsGetRaw(requestParameters);
        return await response.value();
    }

    /**
     */
    async apiProductGetProductByIdIdGetRaw(requestParameters: ApiProductGetProductByIdIdGetRequest): Promise<runtime.ApiResponse<ProductDto>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling apiProductGetProductByIdIdGet.');
        }

        const queryParameters: any = {};

        if (requestParameters.currencyCode !== undefined) {
            queryParameters['currencyCode'] = requestParameters.currencyCode;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/Product/GetProductById/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => ProductDtoFromJSON(jsonValue));
    }

    /**
     */
    async apiProductGetProductByIdIdGet(requestParameters: ApiProductGetProductByIdIdGetRequest): Promise<ProductDto> {
        const response = await this.apiProductGetProductByIdIdGetRaw(requestParameters);
        return await response.value();
    }

}
