/* tslint:disable */
/* eslint-disable */
/**
 * MVCApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    CreateUser,
    CreateUserFromJSON,
    CreateUserToJSON,
} from '../models';

export interface ApiUserCreateUserPostRequest {
    createUser?: CreateUser;
}

/**
 * 
 */
export class UserApi extends runtime.BaseAPI {

    /**
     */
    async apiUserCreateUserPostRaw(requestParameters: ApiUserCreateUserPostRequest): Promise<runtime.ApiResponse<string>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/User/CreateUser`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateUserToJSON(requestParameters.createUser),
        });

        return new runtime.TextApiResponse(response) as any;
    }

    /**
     */
    async apiUserCreateUserPost(requestParameters: ApiUserCreateUserPostRequest): Promise<string> {
        const response = await this.apiUserCreateUserPostRaw(requestParameters);
        return await response.value();
    }

}
