/* tslint:disable */
/* eslint-disable */
/**
 * MVCApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AddProductToCategory
 */
export interface AddProductToCategory {
    /**
     * 
     * @type {string}
     * @memberof AddProductToCategory
     */
    categoryId?: string;
    /**
     * 
     * @type {string}
     * @memberof AddProductToCategory
     */
    productId?: string;
}

export function AddProductToCategoryFromJSON(json: any): AddProductToCategory {
    return AddProductToCategoryFromJSONTyped(json, false);
}

export function AddProductToCategoryFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddProductToCategory {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'categoryId': !exists(json, 'categoryId') ? undefined : json['categoryId'],
        'productId': !exists(json, 'productId') ? undefined : json['productId'],
    };
}

export function AddProductToCategoryToJSON(value?: AddProductToCategory | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'categoryId': value.categoryId,
        'productId': value.productId,
    };
}


