/* tslint:disable */
/* eslint-disable */
/**
 * MVCApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateCategory
 */
export interface CreateCategory {
    /**
     * 
     * @type {string}
     * @memberof CreateCategory
     */
    name?: string | null;
}

export function CreateCategoryFromJSON(json: any): CreateCategory {
    return CreateCategoryFromJSONTyped(json, false);
}

export function CreateCategoryFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateCategory {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
    };
}

export function CreateCategoryToJSON(value?: CreateCategory | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
    };
}


