/* tslint:disable */
/* eslint-disable */
/**
 * MVCApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateSubcategory
 */
export interface CreateSubcategory {
    /**
     * 
     * @type {string}
     * @memberof CreateSubcategory
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateSubcategory
     */
    parentId?: string;
}

export function CreateSubcategoryFromJSON(json: any): CreateSubcategory {
    return CreateSubcategoryFromJSONTyped(json, false);
}

export function CreateSubcategoryFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateSubcategory {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
        'parentId': !exists(json, 'parentId') ? undefined : json['parentId'],
    };
}

export function CreateSubcategoryToJSON(value?: CreateSubcategory | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'parentId': value.parentId,
    };
}


