/* tslint:disable */
/* eslint-disable */
/**
 * MVCApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    CurrencyDto,
    CurrencyDtoFromJSON,
    CurrencyDtoFromJSONTyped,
    CurrencyDtoToJSON,
} from './';

/**
 * 
 * @export
 * @interface CurrencyProductDto
 */
export interface CurrencyProductDto {
    /**
     * 
     * @type {CurrencyDto}
     * @memberof CurrencyProductDto
     */
    currency?: CurrencyDto;
    /**
     * 
     * @type {number}
     * @memberof CurrencyProductDto
     */
    value?: number;
}

export function CurrencyProductDtoFromJSON(json: any): CurrencyProductDto {
    return CurrencyProductDtoFromJSONTyped(json, false);
}

export function CurrencyProductDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CurrencyProductDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'currency': !exists(json, 'currency') ? undefined : CurrencyDtoFromJSON(json['currency']),
        'value': !exists(json, 'value') ? undefined : json['value'],
    };
}

export function CurrencyProductDtoToJSON(value?: CurrencyProductDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'currency': CurrencyDtoToJSON(value.currency),
        'value': value.value,
    };
}


