/* tslint:disable */
/* eslint-disable */
/**
 * MVCApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EditProduct
 */
export interface EditProduct {
    /**
     * 
     * @type {string}
     * @memberof EditProduct
     */
    productId?: string;
    /**
     * 
     * @type {string}
     * @memberof EditProduct
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EditProduct
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EditProduct
     */
    image?: string | null;
}

export function EditProductFromJSON(json: any): EditProduct {
    return EditProductFromJSONTyped(json, false);
}

export function EditProductFromJSONTyped(json: any, ignoreDiscriminator: boolean): EditProduct {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'productId': !exists(json, 'productId') ? undefined : json['productId'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'image': !exists(json, 'image') ? undefined : json['image'],
    };
}

export function EditProductToJSON(value?: EditProduct | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'productId': value.productId,
        'name': value.name,
        'description': value.description,
        'image': value.image,
    };
}


