/* tslint:disable */
/* eslint-disable */
/**
 * MVCApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetAllOrders
 */
export interface GetAllOrders {
    /**
     * 
     * @type {string}
     * @memberof GetAllOrders
     */
    currencyCode?: string | null;
}

export function GetAllOrdersFromJSON(json: any): GetAllOrders {
    return GetAllOrdersFromJSONTyped(json, false);
}

export function GetAllOrdersFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetAllOrders {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'currencyCode': !exists(json, 'currencyCode') ? undefined : json['currencyCode'],
    };
}

export function GetAllOrdersToJSON(value?: GetAllOrders | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'currencyCode': value.currencyCode,
    };
}


