/* tslint:disable */
/* eslint-disable */
/**
 * MVCApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    CurrencyDto,
    CurrencyDtoFromJSON,
    CurrencyDtoFromJSONTyped,
    CurrencyDtoToJSON,
} from './';

/**
 * 
 * @export
 * @interface ImportCurrencies
 */
export interface ImportCurrencies {
    /**
     * 
     * @type {Array<CurrencyDto>}
     * @memberof ImportCurrencies
     */
    currencies?: Array<CurrencyDto> | null;
}

export function ImportCurrenciesFromJSON(json: any): ImportCurrencies {
    return ImportCurrenciesFromJSONTyped(json, false);
}

export function ImportCurrenciesFromJSONTyped(json: any, ignoreDiscriminator: boolean): ImportCurrencies {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'currencies': !exists(json, 'currencies') ? undefined : (json['currencies'] === null ? null : (json['currencies'] as Array<any>).map(CurrencyDtoFromJSON)),
    };
}

export function ImportCurrenciesToJSON(value?: ImportCurrencies | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'currencies': value.currencies === undefined ? undefined : (value.currencies === null ? null : (value.currencies as Array<any>).map(CurrencyDtoToJSON)),
    };
}


