/* tslint:disable */
/* eslint-disable */
/**
 * MVCApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RemoveProductFromCart
 */
export interface RemoveProductFromCart {
    /**
     * 
     * @type {string}
     * @memberof RemoveProductFromCart
     */
    cartId?: string;
    /**
     * 
     * @type {string}
     * @memberof RemoveProductFromCart
     */
    productId?: string;
}

export function RemoveProductFromCartFromJSON(json: any): RemoveProductFromCart {
    return RemoveProductFromCartFromJSONTyped(json, false);
}

export function RemoveProductFromCartFromJSONTyped(json: any, ignoreDiscriminator: boolean): RemoveProductFromCart {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'cartId': !exists(json, 'cartId') ? undefined : json['cartId'],
        'productId': !exists(json, 'productId') ? undefined : json['productId'],
    };
}

export function RemoveProductFromCartToJSON(value?: RemoveProductFromCart | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'cartId': value.cartId,
        'productId': value.productId,
    };
}


